name: 'Actionable'
description: 'Custom MinecraftForge action'
inputs:
  gh_app_key:
    required: true
  gh_app_name:
    required: true
  config_directory:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'