name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  gh_app_key:  # id of input
    required: true
  gh_app_name:  # id of input
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh_app_key }} ${{ inputs.gh_app_name }}