name: 'Actionable'
description: 'Custom MinecraftForge action'
inputs:
  gh_app_key:
    required: true
  gh_app_name:
    required: true
  command_prefixes:
    default: '/'
  allow_commands_in_edits:
    default: 'false'
  triage_team:
    default: 'triage'
  triage_project:
    default: '4'
  labels_to_teams:
    default: 'default -> api, rendering -> rendering, LTS Backport -> legacy'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gh_app_key }} ${{ inputs.gh_app_name }} ${{ inputs.command_prefixes }}