name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  gh_app_key:
    required: true
  gh_app_name:
    required: true
  config_directory:
    required: true
  mode:
    default: 'normal'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'